openapi: 3.0.3
info:
  title: Merchant Participation API
  description: >-
    The API provides information on partner merchants with product code and IPP(Installment Program Providers) relationship.
  contact:
    name: API Support
    email: apisupport@mastercard.com
    url: https://developer.mastercard.com/support
  version: 1.2.0
externalDocs:
  description: ISO 3166 COUNTRY CODES
  url: 'https://www.iso.org/iso-3166-country-codes.html'
servers:
  - url: 'https://sandbox.api.mastercard.com/installments'
    description: Sandbox
  - url: 'https://api.mastercard.com/installments'
    description: Production

tags:
  - name: Merchants Participation
    description: >-
      The API provides information on partner merchants with product code and IPP(Installment Program Providers) relationship.

paths:
  /merchants/participations:
    get:
      tags:
        - Merchants Participation
      summary: Provides list of merchants who have opted in or opted out for a card product.
      description:
        Allows registered IPP to fetch list of merchants who have opted in or opted out for any BNPL installments card products [SPP, SPS, ETA, ETB, ETC, ETD, ETE, ETF, ETG].
        This API will provide merchants details specific to country of Installment Program Provider.

      operationId: getMerchantsParticipations
      parameters:
        - $ref: '#/components/parameters/card_product_code'
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/limit'

      responses:
        '200':
          $ref: '#/components/responses/MerchantParticipation'
        '401':
          $ref: '#/components/responses/AccountNotRegisteredError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '406':
          $ref: '#/components/responses/NotAcceptableHeader'


components:
  parameters:
    card_product_code:
      in: query
      name: card_product_code
      description: Codes of the products such as ETA - ETG, SPP, and SPS
      required: false
      schema:
        type: string
        enum: [ETA,ETB,ETC,ETD,ETE,ETF,ETG,SPP,SPS]
        pattern: ^(?:ETA|ETB|ETC|ETD|ETE|ETF|ETG|SPP|SPS)$
      example: SPS

    offset:
      in: query
      name: offset
      description: The number of items you need the start of the list to be offset from.
      required: false
      schema:
        type: integer
        default: 0
        minimum: 0
      example: 100
    limit:
      in: query
      name: limit
      description: The number of items you asked the list to be limited to.
      required: false
      schema:
        type: integer
        default: 500
        minimum: 50
        maximum: 500
      example: 100

  responses:
    MerchantParticipation:
      description:
        The response object that contains list of merchants who have opted in or opted out for given card product
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MerchantParticipation'
          examples:
            Preference:
              $ref: '#/components/examples/MerchantParticipation'

    AccountNotRegisteredError:
      description:
        This response code is returned when server cannot find the account which has been used to call this API.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorWrapper'
          examples:
            AccountNotRegisteredError:
              $ref: '#/components/examples/AccountNotRegisteredError'

    ForbiddenError:
      description:
        This response code is returned when API or resource access is not approved for the client.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorWrapper'
          examples:
            ForbiddenError:
              $ref: '#/components/examples/ForbiddenError'

    BadRequestError:
      description:
        This response code is returned when a request is invalid, or data in the
        request is not valid.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorWrapper'
          examples:
            InvalidCardProductError:
              $ref: '#/components/examples/InvalidCardProductError'

    NotAcceptableHeader:
      description: >-
        This response code is returned when user enters anything except application/json in Accept header.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorWrapper'
          examples:
            NotAcceptableHeader:
              $ref: '#/components/examples/NotAcceptableHeader'


  schemas:
    MerchantParticipation:
      title: MerchantParticipation
      type: object
      description:
        Contains the list of merchant who have opted in or opted out for a card product
      required:
        - merchants
      properties:
        count:
          description: The number of items in this batch (the size of the item array).
          type: integer
          example: 2
        offset:
          description: The number of items you asked the start of the list to be offset from.
          type: integer
          example: 1
        limit:
          description: The number of items you asked the list to be limited to.
          type: integer
          example: 2
        total:
          description: The total number of items in the collection.
          type: integer
          example: 5
        merchants:
          $ref: '#/components/schemas/Merchants'

    Wallets:
      title: Wallets
      type: array
      minItems: 1
      maxItems: 500
      description:
        API will return the list of wallet name, wallet acceptance, and wallet merchant id.
      items:
        $ref: '#/components/schemas/Wallet'

    Wallet:
      type: object
      description: Object representing registering a Merchant
      properties:
        walletName:
          type: string
          minLength: 1
          maxLength: 200
          description: Wallet provider that have a relationship with the given merchant
          example: Apple Pay
        walletAcceptance:
          type: string
          maxLength: 1
          minLength: 1
          pattern: ^(?:Y|N)$
          description: Wallet acceptance for the given wallet provider
          example: Y
        walletMerchantId:
          type: string
          minLength: 1
          maxLength: 2000
          description: Merchant identifier(s) as defined by the wallet provider
          example: 235346356234
      example:
        walletName: Apple Pay
        walletAcceptance: Y
        walletMerchantId: 235346356234 | 125346356236 | 125446356237

    CardProducts:
      title: CardProducts
      type: array
      minItems: 1
      maxItems: 500
      description:
        List of card product objects
      items:
        $ref: '#/components/schemas/CardProduct'

    CardProduct:
      type: object
      description: Object representing card product
      required:
        - productCode
        - optIn
      properties:
        productCode:
          type: string
          minLength: 1
          maxLength: 3
          pattern: ^(?:ETA|ETB|ETC|ETD|ETE|ETF|ETG|SPP|SPS)$
          description: Codes of the products such as ETA - ETG, SPP, and SPS
          example: SPS
        optIn:
          type: string
          maxLength: 1
          minLength: 1
          pattern: ^(?:Y|N)$
          description: Merchant opt-in or opt-out preference
          example: Y
      example:
        productCode: SPS
        optIn: Y

    Address:
      title: Address
      type: object
      description:
        Object representing a merchant address
      required:
        - addressLine1
        - city
        - state
        - postalCode
      properties:
        addressLine1:
          type: string
          minLength: 1
          maxLength: 80
          description: Legally registered address of the merchant
          example: 600 WEST
        addressLine2:
          type: string
          minLength: 1
          maxLength: 80
          description: Second address
          example: SECTOR 5
        addressLine3:
          type: string
          minLength: 1
          maxLength: 80
          description: Third address line
          example: SUITE 775
        city:
          type: string
          minLength: 1
          maxLength: 30
          description: Legally registered address city.
          example: St Peters
        state:
          type: string
          minLength: 2
          maxLength: 3
          description: Legally registered address state or province. Refer to (https://www.iso.org/obp/ui/#search) for ISO 3166-2 code values.
          example: QLD
        postalCode:
          type: string
          minLength: 1
          maxLength: 20
          description: Legally registered address postal code.
          example: 85001

      example:
        addressLineOne: 600 WEST
        addressLineTwo: SECTOR 5
        addressLineThree: SUITE 775
        city: Chicago
        state: MO
        postalCode: 85001

    Merchants:
      title: Merchants
      type: array
      minItems: 1
      maxItems: 500
      description:
        List of merchant objects
      items:
        $ref: '#/components/schemas/Merchant'

    Merchant:
      type: object
      description: Merchant details
      required:
        - customerId
        - companyName
        - countryCode
        - products
        - lastUpdateDatetime
      properties:
        customerId:
          type: integer
          format: int64
          minLength: 1
          maxLength: 10
          description: Primary key to identify unique company or merchant, assigned by Mastercard.
          example: 9870152892
        duns:
          type: string
          minLength: 1
          maxLength: 9
          description: A unique identifier assigned by Dun and Bradstreet used to identify a business.
          example: 879847426
        acceptorIds:
          type: array
          minItems: 1
          description: A value assigned by Mastercard for transaction data integrity purposes
          items:
            type: string
          example: ["123456","789101"]
        companyName:
          type: string
          minLength: 1
          maxLength: 300
          description: Legally registered name of the merchant.
          pattern: '^.{1,300}'
          example: Walmart
        dbaName:
          type: string
          minLength: 1
          maxLength: 256
          description: Trade name used by merchant to conduct business, and is known to the consumer.
          example: ACME
        customerReferenceUrlAddress:
          type: string
          minLength: 1
          maxLength: 100
          pattern: '^(https?|ftp|file)://[-a-zA-Z0-9+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9+&@#/%=~_|]'
          description: The URL of the merchant supplied to the acquirer.
          example: https://www.acme-company.com
        countryCode:
          type: string
          minLength: 3
          maxLength: 3
          pattern: '^[A-Za-z]{3}$'
          description: Legally registered address country. Refer to (https://www.iso.org/obp/ui/#search) for ISO 3166 alpha 3 code values.
          example: USA
        lastUpdateDatetime:
          type: string
          format: date-time
          description: Time when this record is last updated,this field will be as per ISO8601 and RFC 3339. (https://confluence.mastercard.int/display/GoldenAPI/Mastercard+Global+API+Standards+Document#MastercardGlobalAPIStandardsDocument-DateTimeFormatting).
          example: '2021-11-02T12:31:26'
        wallets:
          $ref: '#/components/schemas/Wallets'
        products:
          $ref: '#/components/schemas/CardProducts'
        address:
          $ref: '#/components/schemas/Address'


      example:
        customerId: 9870152892
        duns: 9870152892
        acceptorIds: ["54331", "123456"]
        companyName: Walmart
        dbaName: ACME
        customerReferenceUrlAddress: https://www.acme-company.com
        addressLineOne: 600 WEST
        addressLineTwo: SECTOR 5
        addressLineThree: SUITE 775
        city: Chicago
        state: MO
        countryCode: USA
        postalCode: 85001
        productCode: SPS
        walletName: Apple Pay
        walletAcceptance: Y
        walletMerchantId: 114573524
        optIn: Y
        lastUpdateDatetime: 2020-07-16T19:20+01:00

    ErrorWrapper:
      title: ErrorWrapper
      type: object
      description: The error response object which gets returned in case of any error.
      required:
        - Errors
      properties:
        Errors:
          $ref: '#/components/schemas/Errors'
    Errors:
      title: Errors
      type: object
      description: Error object which returns list of Error objects.
      required:
        - Error
      properties:
        Error:
          $ref: '#/components/schemas/ErrorList'
    ErrorList:
      type: array
      minItems: 1
      items:
        $ref: '#/components/schemas/Error'
    Error:
      title: Error
      type: object
      description: Error object which contains details about error.
      required:
        - Source
        - ReasonCode
        - Description
        - Recoverable
      properties:
        Source:
          type: string
          description:
            The application name that generated this error.
          minLength: 1
          maxLength: 100
          example: Service-Provider
        ReasonCode:
          type: string
          description:
            A unique constant identifying the error case encountered during
            request processing.
          minLength: 1
          maxLength: 100
          example: invalid.request.parameter
        Description:
          type: string
          description: Short description of the ReasonCode field.
          minLength: 10
          maxLength: 1000
          example:
            One of the request parameters is invalid, try again with correct
            request.
        Recoverable:
          type: boolean
          description:
            Indicates whether this error will always be returned for this
            request, or retrying could change the outcome.
          example: false
        Details:
          type: string
          description:
            (Optional) Where appropriate, indicates detailed information about
            data received and calculated during request processing, to help the
            user with diagnosing errors.
          minLength: 0
          maxLength: 5000
          example: paymentCardId size must be between 36 and 36


  examples:
    MerchantParticipation:
      value:
        count: 2
        offset: 1
        limit: 2
        total: 5
        merchants:
          - customerId: 9870152892
            duns: 879847416
            acceptorIds:
              - 54331
              - 123456
            companyName: Walmart
            dbaName: ACME
            companyUrl: www.momentum-bike.com
            country: USA
            postalCode: 99202
            wallets:
              - walletName: Apple Pay
                walletAcceptance: Y
                walletMerchantId: 235346356234
              - walletName: Google Pay
                walletAcceptance: N
                walletMerchantId: 125346356236
            address:
              addressLineOne: 600 WEST
              addressLineTwo: SECTOR 5
              addressLineThree: SUITE 775
              city: Chicago
              state: MO
              postalCode: 85001
            products:
              - productCode: SPS
                optIn: N
              - productCode: ETA
                optIn: Y
            lastUpdateDatetime: 2020-07-16T19:20+01:00

    AccountNotRegisteredError:
      value:
        Errors:
          Error:
            - Source: customer-data-api
              ReasonCode: account.not.registered
              Description:
                We cannot find the account which you are using to access this
                service. Kindly register your account or contact your Mastercard
                associate if you have already registered with us earlier.
              Recoverable: false
              Details: ''

    ForbiddenError:
      value:
        Errors:
          Error:
            - Source: customer-data-api
              ReasonCode: forbidden
              Description:
                Your account is not approved to access the API or resource, kindly contact your
                Mastercard associate to get approval.
              Recoverable: false
              Details: ''

    NotAcceptableHeader:
      value:
        Errors:
          Error:
            - Source: customer-data-api
              ReasonCode: not.acceptable.header
              Description: >-
                Accept header value is not application/json.
              Recoverable: false
              Details: ''

    InvalidCardProductError:
      value:
        Errors:
          Error:
            - Source: customer-data-api
              ReasonCode: invalid.request.parameter
              Description:
                Product SPP is not available for IND country
              Recoverable: false
              Details: ''